"""empty message

Revision ID: 06d7ce91d392
Revises: df51cd9b658f
Create Date: 2024-02-25 13:46:10.094754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d7ce91d392'
down_revision = 'df51cd9b658f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_served', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('date_served')

    # ### end Alembic commands ###
