"""empty message

Revision ID: 0e311cffd25d
Revises: ca3431191dc9
Create Date: 2024-02-25 14:20:05.960332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e311cffd25d'
down_revision = 'ca3431191dc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('date_served',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('date_served',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
