"""empty message

Revision ID: c8f217bb54f7
Revises: 
Create Date: 2024-02-25 02:06:33.198624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8f217bb54f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_served', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('location_input', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('summarized_descrition', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('served_by', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('medicine', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('disease', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('doctor', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('doctor')
        batch_op.drop_column('disease')
        batch_op.drop_column('medicine')
        batch_op.drop_column('served_by')
        batch_op.drop_column('summarized_descrition')
        batch_op.drop_column('location_input')
        batch_op.drop_column('date_served')

    # ### end Alembic commands ###
