"""empty message

Revision ID: f9fc4f8347bb
Revises: 06d7ce91d392
Create Date: 2024-02-25 13:54:54.311576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9fc4f8347bb'
down_revision = '06d7ce91d392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('date_served')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_served', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
